language: node_js
node_js:
- '11'
cache: npm

env:
  global:
    secure: fWmEL2VdJLBcXA2h16nqYuFoIj1XdO7CsII1FM+AxuBuyfHW9eevY2eu18rV0yBRFzZlie8iAgLdes0Rs0EGLBBvj5LqK7DPw4fntCm3mU3BUNwSeTzdiec2LJ3Gr1IYoiIAQ4k6evJrCMLNUG2e5/H/NF8TL3wjK+FMwewrUtHdysBOd0eFm1ZJ02ySOhpd90n+HLVWnYpU6E9gYN8J6pfYgYsv+04cs6OTJDBOq++6zrqCgoiv4Cs6vk2BDamNSJRD0y5Ux6NLynQNU2xcxlYOaqPAWw3NBiJqPNANDE2w9achOd14ATT42tiVWTqYdVi+1K31Ww3lqtoXzFFcg8EeDUbcDwrHMxomBvB3jZmtbPzeJXQKCRsAKRZiL+iisl9ahJHKyycv5kd9ChGM4cekO4xTztn1I3ecigAgrsATfrDMIwsKNPfax+BNKNUv8LVG9IY3tCk+ZGx29mhNhgMXSeW6Sv1F9Hq1CTgNl6Ss3ZUoT+gmL4IJCl17BKmW7inZwqYcff5ujJPkHpdeI+TnOmf4vTOftXW7Wy7su2QV1Zw8QospZmahGAjgEcmPE8LTBZ1hy1K3rXRVrVDT96D7tMhJHNuq58yFsr4+h+Igq2R0mvHNsy0twT4/WomhvLW+XewCOTAk1Vii1E9fTz46+2spVFEXNEwnfOMwbhs=
